services:

  web:
    build: .
    image: ptscheduler-web
    container_name: PTScheduler
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: >-
        Host=192.168.0.220;Port=5432;Database=ptscheduler;
        Username=postgres;Password=postgres
    volumes:
      - /mnt/user/appdata/ptscheduler/uploads:/app/wwwroot/uploads
