// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTScheduler.Portal.Data;

#nullable disable

namespace PTScheduler.Portal.Data.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20261003074706_RegistrationPayments")]
    partial class RegistrationPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.AppFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicAuthor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("AppFeedbacks");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.BackupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OffsiteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OffsiteInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("OffsiteOk")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifyInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("VerifyOk")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Slug");

                    b.ToTable("BackupEntries");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.GoogleCalendarGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserKey")
                        .IsUnique();

                    b.ToTable("GoogleCalendarGrants");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.InviteCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtraTrialDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("text");

                    b.Property<int?>("ServiceOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeInvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalPaymentId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("StripeInvoiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AdvancedAnalytics")
                        .HasColumnType("boolean");

                    b.Property<bool>("AuditLog")
                        .HasColumnType("boolean");

                    b.Property<bool>("BasicAnalytics")
                        .HasColumnType("boolean");

                    b.Property<bool>("BodyMeasurements")
                        .HasColumnType("boolean");

                    b.Property<string>("BrandingTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ClientReports")
                        .HasColumnType("boolean");

                    b.Property<bool>("Coupons")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoursesEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CustomDomain")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomEmailTemplates")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomFavicon")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomLogo")
                        .HasColumnType("boolean");

                    b.Property<bool>("DataExport")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EmailReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("FinancialReports")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationGoogleMeet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationPayU")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationPrzelewy24")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxClients")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCourses")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSmsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSubordinates")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTrainers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoBandwidthGBPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoStorageGB")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PaymentsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecurringSessions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReferralProgram")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoleBasedAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmsReminders")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripeMonthlyPriceId")
                        .HasColumnType("text");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("text");

                    b.Property<string>("StripeYearlyPriceId")
                        .HasColumnType("text");

                    b.Property<bool>("TrainingPlansEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("YearlyPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = "start",
                            AdvancedAnalytics = false,
                            AuditLog = false,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            BrandingTier = "preview",
                            ClientReports = false,
                            Coupons = false,
                            CoursesEnabled = false,
                            Currency = "PLN",
                            CustomDomain = false,
                            CustomEmailTemplates = false,
                            CustomFavicon = false,
                            CustomLogo = false,
                            DataExport = false,
                            Description = "Testuj za darmo przez 7 dni",
                            EmailReminders = true,
                            FinancialReports = false,
                            IntegrationGoogleMeet = false,
                            IntegrationPayU = false,
                            IntegrationPrzelewy24 = false,
                            IsActive = true,
                            IsFeatured = false,
                            MaxClients = 3,
                            MaxCourses = 0,
                            MaxSessionsPerMonth = 30,
                            MaxSmsPerMonth = 0,
                            MaxStorageGB = 1,
                            MaxSubordinates = 0,
                            MaxTrainers = 0,
                            MaxVideoBandwidthGBPerMonth = 0,
                            MaxVideoStorageGB = 0,
                            MonthlyPrice = 0m,
                            Name = "Start",
                            PaymentsEnabled = false,
                            PushNotifications = false,
                            RecurringSessions = true,
                            ReferralProgram = false,
                            RoleBasedAccess = false,
                            SmsReminders = false,
                            SortOrder = 1,
                            TrainingPlansEnabled = false,
                            TrialDays = 7,
                            TwoFactorAuth = true,
                            VideoProvider = "youtube"
                        },
                        new
                        {
                            Id = "starter",
                            AdvancedAnalytics = false,
                            AuditLog = false,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            BrandingTier = "basic",
                            ClientReports = false,
                            Coupons = false,
                            CoursesEnabled = false,
                            Currency = "PLN",
                            CustomDomain = false,
                            CustomEmailTemplates = false,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = false,
                            Description = "Podstawowe narzędzia dla trenera",
                            EmailReminders = true,
                            FinancialReports = true,
                            IntegrationGoogleMeet = false,
                            IntegrationPayU = true,
                            IntegrationPrzelewy24 = false,
                            IsActive = true,
                            IsFeatured = false,
                            MaxClients = 15,
                            MaxCourses = 3,
                            MaxSessionsPerMonth = 200,
                            MaxSmsPerMonth = 0,
                            MaxStorageGB = 5,
                            MaxSubordinates = 0,
                            MaxTrainers = 0,
                            MaxVideoBandwidthGBPerMonth = 0,
                            MaxVideoStorageGB = 5,
                            MonthlyPrice = 49m,
                            Name = "Starter",
                            PaymentsEnabled = true,
                            PushNotifications = false,
                            RecurringSessions = true,
                            ReferralProgram = false,
                            RoleBasedAccess = false,
                            SmsReminders = false,
                            SortOrder = 2,
                            TrainingPlansEnabled = false,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "youtube",
                            YearlyPrice = 490m
                        },
                        new
                        {
                            Id = "pro",
                            AdvancedAnalytics = true,
                            AuditLog = false,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            BrandingTier = "full",
                            ClientReports = true,
                            Coupons = true,
                            CoursesEnabled = true,
                            Currency = "PLN",
                            CustomDomain = false,
                            CustomEmailTemplates = true,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = true,
                            Description = "Pełna funkcjonalność dla aktywnych trenerów",
                            EmailReminders = true,
                            FinancialReports = true,
                            IntegrationGoogleMeet = true,
                            IntegrationPayU = true,
                            IntegrationPrzelewy24 = true,
                            IsActive = true,
                            IsFeatured = true,
                            MaxClients = 50,
                            MaxCourses = 10,
                            MaxSessionsPerMonth = 500,
                            MaxSmsPerMonth = 50,
                            MaxStorageGB = 10,
                            MaxSubordinates = 1,
                            MaxTrainers = 2,
                            MaxVideoBandwidthGBPerMonth = 100,
                            MaxVideoStorageGB = 20,
                            MonthlyPrice = 99m,
                            Name = "Pro",
                            PaymentsEnabled = true,
                            PushNotifications = true,
                            RecurringSessions = true,
                            ReferralProgram = true,
                            RoleBasedAccess = false,
                            SmsReminders = true,
                            SortOrder = 3,
                            TrainingPlansEnabled = true,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "bunny",
                            YearlyPrice = 990m
                        },
                        new
                        {
                            Id = "studio",
                            AdvancedAnalytics = true,
                            AuditLog = true,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            BrandingTier = "premium",
                            ClientReports = true,
                            Coupons = true,
                            CoursesEnabled = true,
                            Currency = "PLN",
                            CustomDomain = false,
                            CustomEmailTemplates = true,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = true,
                            Description = "Bez limitów, pełna kontrola, priorytetowe wsparcie",
                            EmailReminders = true,
                            FinancialReports = true,
                            IntegrationGoogleMeet = true,
                            IntegrationPayU = true,
                            IntegrationPrzelewy24 = true,
                            IsActive = true,
                            IsFeatured = false,
                            MaxClients = 2147483647,
                            MaxCourses = 2147483647,
                            MaxSessionsPerMonth = 2147483647,
                            MaxSmsPerMonth = 500,
                            MaxStorageGB = 100,
                            MaxSubordinates = 5,
                            MaxTrainers = 10,
                            MaxVideoBandwidthGBPerMonth = 1000,
                            MaxVideoStorageGB = 200,
                            MonthlyPrice = 199m,
                            Name = "Business",
                            PaymentsEnabled = true,
                            PushNotifications = true,
                            RecurringSessions = true,
                            ReferralProgram = true,
                            RoleBasedAccess = true,
                            SmsReminders = true,
                            SortOrder = 4,
                            TrainingPlansEnabled = true,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "bunny",
                            YearlyPrice = 1990m
                        });
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.ResourceSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("BackupDiskTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("BackupDiskUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("CpuCores")
                        .HasColumnType("double precision");

                    b.Property<double?>("CpuLimitCores")
                        .HasColumnType("double precision");

                    b.Property<long?>("DbMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("DbSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiskTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiskUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("FilesBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<long?>("WebMemoryBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("TenantId", "At");

                    b.ToTable("ResourceSamples");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("manual");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("FulfillmentType");

                    b.HasIndex("IsActive");

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "branding",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 30m,
                            Description = "Wymiana logo, dopasowanie kolorystyki i motywu strony trenera.",
                            FulfillmentType = "manual",
                            Icon = "bi-palette",
                            IsActive = true,
                            Name = "Zmiana logo / kolorów strony",
                            PriceType = "one_time",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "setup",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 30m,
                            Description = "Ustawienie typów wizyt, godzin pracy, cyklicznych zajęć.",
                            FulfillmentType = "manual",
                            Icon = "bi-calendar-week",
                            IsActive = true,
                            Name = "Konfiguracja grafiku zajęć",
                            PriceType = "one_time",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "setup",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 50m,
                            Description = "Konfiguracja PayU lub Przelewy24, testowanie procesu płatności.",
                            FulfillmentType = "manual",
                            Icon = "bi-credit-card",
                            IsActive = true,
                            Name = "Ustawienie płatności online",
                            PriceType = "one_time",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "setup",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 50m,
                            Description = "Import listy klientów z pliku Excel/CSV do systemu.",
                            FulfillmentType = "manual",
                            Icon = "bi-people",
                            IsActive = true,
                            Name = "Import bazy klientów",
                            PriceType = "one_time",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "training",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 80m,
                            Description = "Indywidualne szkolenie wideo z obsługi systemu.",
                            FulfillmentType = "manual",
                            Icon = "bi-camera-video",
                            IsActive = true,
                            Name = "Szkolenie 1:1 (30 min)",
                            PriceType = "one_time",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "setup",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 150m,
                            Description = "Kompleksowe ustawienie strony: branding, grafik, usługi, płatności.",
                            FulfillmentType = "manual",
                            Icon = "bi-wrench-adjustable",
                            IsActive = true,
                            Name = "Pełna konfiguracja strony",
                            PriceType = "one_time",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "support",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 29m,
                            Description = "2 drobne zmiany/mies., email 24h, 1 szkolenie/kwartał.",
                            FulfillmentType = "manual",
                            Icon = "bi-headset",
                            IsActive = true,
                            Name = "Pakiet Wsparcie Podstawowy",
                            PriceType = "monthly",
                            SortOrder = 10,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 8,
                            Category = "support",
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0,
                            DefaultPrice = 79m,
                            Description = "Bez limitu drobnych zmian, priorytet + telefon, 1 szkolenie/mies.",
                            FulfillmentType = "manual",
                            Icon = "bi-star",
                            IsActive = true,
                            Name = "Pakiet Wsparcie Premium",
                            PriceType = "monthly",
                            SortOrder = 11,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 100,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 100,
                            DefaultPrice = 19m,
                            Description = "100 SMS-ów więcej co miesiąc na przypomnienia o treningach. Doliczane do abonamentu — rezygnujesz, kiedy chcesz.",
                            FulfillmentType = "credit_sms",
                            Icon = "bi-chat-dots",
                            IsActive = true,
                            Name = "SMS +100 miesięcznie",
                            PriceType = "monthly",
                            SortOrder = 20,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 101,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 300,
                            DefaultPrice = 49m,
                            Description = "300 SMS-ów więcej co miesiąc — dla studiów z dużą liczbą klientów. Doliczane do abonamentu.",
                            FulfillmentType = "credit_sms",
                            Icon = "bi-chat-dots",
                            IsActive = true,
                            Name = "SMS +300 miesięcznie",
                            PriceType = "monthly",
                            SortOrder = 21,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 102,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 100,
                            DefaultPrice = 29m,
                            Description = "Na wyjątkowo pracowity miesiąc: SMS-y nie wygasają i schodzą dopiero po wyczerpaniu miesięcznego limitu.",
                            FulfillmentType = "credit_sms",
                            Icon = "bi-chat-dots",
                            IsActive = true,
                            Name = "Jednorazowe doładowanie 100 SMS",
                            PriceType = "one_time",
                            SortOrder = 22,
                            Unit = "100 szt."
                        },
                        new
                        {
                            Id = 110,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 10,
                            DefaultPrice = 15m,
                            Description = "10 GB więcej na lekcje i instruktaże wideo, dopóki dodatek jest aktywny. Doliczane do abonamentu.",
                            FulfillmentType = "credit_cdn_storage",
                            Icon = "bi-cloud-upload",
                            IsActive = true,
                            Name = "Wideo +10 GB miejsca",
                            PriceType = "monthly",
                            SortOrder = 30,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 111,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 50,
                            DefaultPrice = 49m,
                            Description = "50 GB więcej na kursy wideo — dla rozbudowanej biblioteki ćwiczeń i programów. Doliczane do abonamentu.",
                            FulfillmentType = "credit_cdn_storage",
                            Icon = "bi-cloud-upload",
                            IsActive = true,
                            Name = "Wideo +50 GB miejsca",
                            PriceType = "monthly",
                            SortOrder = 31,
                            Unit = "miesiąc"
                        },
                        new
                        {
                            Id = 120,
                            Category = "addon",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 100,
                            DefaultPrice = 25m,
                            Description = "Podnosi miesięczny limit odtwarzania kursów wideo o 100 GB. Doliczane do abonamentu — rezygnujesz, kiedy chcesz.",
                            FulfillmentType = "credit_cdn_bandwidth",
                            Icon = "bi-speedometer2",
                            IsActive = true,
                            Name = "Transfer wideo +100 GB miesięcznie",
                            PriceType = "monthly",
                            SortOrder = 32,
                            Unit = "miesiąc"
                        });
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ChargedToBillAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderGroupId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentExternalId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentGateway")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderGroupId");

                    b.HasIndex("PaymentExternalId");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BunnyCdnHostname")
                        .HasColumnType("text");

                    b.Property<string>("BunnyLibraryApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BunnyLibraryId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomDomainSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomainStatus")
                        .HasColumnType("text");

                    b.Property<string>("DbContainerName")
                        .HasColumnType("text");

                    b.Property<string>("DbPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DownAlertSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GraceUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalSecret")
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text");

                    b.Property<bool?>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastActivityCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastHealthError")
                        .HasColumnType("text");

                    b.Property<int?>("LastHealthResponseMs")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueuedReason")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationPaymentGateway")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("SetupMode")
                        .HasColumnType("text");

                    b.Property<string>("SetupPayload")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnhealthySinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebContainerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("Port")
                        .IsUnique();

                    b.HasIndex("RegistrationKey");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StripeSubscriptionItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("TenantAddons");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidVia")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PayToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PaymentExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PaymentSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PayToken")
                        .IsUnique();

                    b.HasIndex("PaymentExternalId");

                    b.HasIndex("PaymentSessionId");

                    b.HasIndex("TenantId", "PeriodStart");

                    b.ToTable("TenantBills");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantBillLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OfferItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("TenantBillLines");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPurchased")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalUsed")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreditType")
                        .IsUnique();

                    b.ToTable("TenantCredits");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantEvents");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantMailCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Day")
                        .IsUnique();

                    b.ToTable("TenantMailCounters");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantOfferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Billing")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("EffectAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EffectAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantOfferItems");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantServicePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustomPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("TenantId", "ServiceItemId")
                        .IsUnique();

                    b.ToTable("TenantServicePrices");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantSmsCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Month")
                        .IsUnique();

                    b.ToTable("TenantSmsCounters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.AppFeedback", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.GoogleCalendarGrant", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.PaymentRecord", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId");

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.ServiceOrder", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Subscription", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Plan", "Plan")
                        .WithMany("Tenants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantAddon", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantBill", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantBillLine", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.TenantBill", "Bill")
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantCredit", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantEvent", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantMailCounter", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantOfferItem", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantServicePrice", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantSmsCounter", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Plan", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantBill", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
