// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PTScheduler.Portal.Data;

#nullable disable

namespace PTScheduler.Portal.Data.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260826140000_AddPaymentRecordsAndTenantEvents")]
    partial class AddPaymentRecordsAndTenantEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.BackupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Slug");

                    b.ToTable("BackupEntries");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AdvancedAnalytics")
                        .HasColumnType("boolean");

                    b.Property<bool>("AuditLog")
                        .HasColumnType("boolean");

                    b.Property<bool>("BasicAnalytics")
                        .HasColumnType("boolean");

                    b.Property<bool>("BodyMeasurements")
                        .HasColumnType("boolean");

                    b.Property<bool>("ClientReports")
                        .HasColumnType("boolean");

                    b.Property<bool>("Coupons")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoursesEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CustomEmailTemplates")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomFavicon")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomLogo")
                        .HasColumnType("boolean");

                    b.Property<bool>("DataExport")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EmailReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("FinancialReports")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationGoogleMeet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationPayU")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegrationPrzelewy24")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxClients")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCourses")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSmsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSubordinates")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTrainers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoBandwidthGBPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoStorageGB")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PaymentsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecurringSessions")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoleBasedAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmsReminders")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripeMonthlyPriceId")
                        .HasColumnType("text");

                    b.Property<string>("StripeYearlyPriceId")
                        .HasColumnType("text");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("YearlyPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = "start",
                            AdvancedAnalytics = false,
                            AuditLog = false,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            ClientReports = false,
                            Coupons = false,
                            CoursesEnabled = false,
                            Currency = "PLN",
                            CustomEmailTemplates = false,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = false,
                            Description = "Dla trenera, który zaczyna",
                            EmailReminders = true,
                            FinancialReports = false,
                            IntegrationGoogleMeet = false,
                            IntegrationPayU = false,
                            IntegrationPrzelewy24 = false,
                            IsActive = true,
                            IsFeatured = false,
                            MaxClients = 3,
                            MaxCourses = 0,
                            MaxSessionsPerMonth = 30,
                            MaxSmsPerMonth = 0,
                            MaxStorageGB = 1,
                            MaxSubordinates = 0,
                            MaxTrainers = 0,
                            MaxVideoBandwidthGBPerMonth = 0,
                            MaxVideoStorageGB = 0,
                            MonthlyPrice = 0m,
                            Name = "Start",
                            PaymentsEnabled = false,
                            PushNotifications = false,
                            RecurringSessions = true,
                            RoleBasedAccess = false,
                            SmsReminders = false,
                            SortOrder = 1,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "youtube"
                        },
                        new
                        {
                            Id = "pro",
                            AdvancedAnalytics = true,
                            AuditLog = false,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            ClientReports = true,
                            Coupons = true,
                            CoursesEnabled = true,
                            Currency = "PLN",
                            CustomEmailTemplates = true,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = true,
                            Description = "Pełna funkcjonalność dla aktywnych trenerów",
                            EmailReminders = true,
                            FinancialReports = true,
                            IntegrationGoogleMeet = true,
                            IntegrationPayU = true,
                            IntegrationPrzelewy24 = true,
                            IsActive = true,
                            IsFeatured = true,
                            MaxClients = 50,
                            MaxCourses = 10,
                            MaxSessionsPerMonth = 500,
                            MaxSmsPerMonth = 50,
                            MaxStorageGB = 10,
                            MaxSubordinates = 1,
                            MaxTrainers = 2,
                            MaxVideoBandwidthGBPerMonth = 100,
                            MaxVideoStorageGB = 20,
                            MonthlyPrice = 79m,
                            Name = "Pro",
                            PaymentsEnabled = true,
                            PushNotifications = true,
                            RecurringSessions = true,
                            RoleBasedAccess = false,
                            SmsReminders = true,
                            SortOrder = 2,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "bunny",
                            YearlyPrice = 790m
                        },
                        new
                        {
                            Id = "studio",
                            AdvancedAnalytics = true,
                            AuditLog = true,
                            BasicAnalytics = true,
                            BodyMeasurements = true,
                            ClientReports = true,
                            Coupons = true,
                            CoursesEnabled = true,
                            Currency = "PLN",
                            CustomEmailTemplates = true,
                            CustomFavicon = true,
                            CustomLogo = true,
                            DataExport = true,
                            Description = "Bez limitów, pełna kontrola, priorytetowe wsparcie",
                            EmailReminders = true,
                            FinancialReports = true,
                            IntegrationGoogleMeet = true,
                            IntegrationPayU = true,
                            IntegrationPrzelewy24 = true,
                            IsActive = true,
                            IsFeatured = false,
                            MaxClients = 2147483647,
                            MaxCourses = 2147483647,
                            MaxSessionsPerMonth = 2147483647,
                            MaxSmsPerMonth = 500,
                            MaxStorageGB = 100,
                            MaxSubordinates = 5,
                            MaxTrainers = 10,
                            MaxVideoBandwidthGBPerMonth = 1000,
                            MaxVideoStorageGB = 200,
                            MonthlyPrice = 149m,
                            Name = "Studio",
                            PaymentsEnabled = true,
                            PushNotifications = true,
                            RecurringSessions = true,
                            RoleBasedAccess = true,
                            SmsReminders = true,
                            SortOrder = 3,
                            TrialDays = 14,
                            TwoFactorAuth = true,
                            VideoProvider = "bunny",
                            YearlyPrice = 1490m
                        });
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeInvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StripeInvoiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantEvents");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DbContainerName")
                        .HasColumnType("text");

                    b.Property<string>("DbPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DownAlertSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastHealthError")
                        .HasColumnType("text");

                    b.Property<int?>("LastHealthResponseMs")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetupMode")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnhealthySinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebContainerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("Port")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.PaymentRecord", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Subscription", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.TenantEvent", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.HasOne("PTScheduler.Portal.Entities.Plan", "Plan")
                        .WithMany("Tenants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Plan", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PTScheduler.Portal.Entities.Tenant", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
